// Divine DunlopDreams Collection — product data for the two category descriptions.
// Every fact below was read from the live product page (the model's `url`) on 2026-10-10.
// Nothing is copied from the hero without that check: where the hero 1.17.1 data differs from the live page, the live page wins
// (see CAPABILITY-REPORT.md §5 "Product data verification").
// No prices, by design. No gendered wording. Firmness codes: s Soft, m Medium, f Firm, x Extra Firm.

export const HERO_ASSETS = 'https://cdn.jsdelivr.net/gh/Matrress/Animation@57479ca18f8e6bab02e2a4aa0ec4f0cf82578fad/divine-hero/release/1.17.1/assets/';

export const FIRM = { s: 'Soft', m: 'Medium', f: 'Firm', x: 'Extra Firm' };

export const collections = {
  mattress: {
    key: 'mattress',
    label: 'Latex Mattresses Collection',
    url: 'https://divinedunlop.com/products/latex-mattresses-collection',
    question: 'Which 100% latex mattress is right for you?',
    lede: 'Eight latex mattresses, one material: natural Dunlop latex. Each exists for a reason. Open a model to set its size, firmness, depth and cover.',
    buy: 'Next: on the model page choose your size, firmness, depth and cover, then add to bag.',
    footer: ['Pure latex sleep systems: no springs, no memory foam, no synthetic foam core.', 'Dual Plush: a latex mattress for support and a separate latex topper for comfort, chosen together.', 'Made to order in your size, firmness, depth and cover.'],
    navLabel: 'The latex mattress collection, by family',
    pick: 'Choose a model to preview',
    steps: ['Pick your model', 'Set size, firmness, thickness & cover', 'Buy'],
    stepNotes: ['here', 'on the model page', 'on the model page'],
    principles: [
      ['Pure latex sleep systems', 'No springs, no memory foam, no synthetic foam core.'],
      ['Layers with a job', 'Where a model has layers, they regulate support, comfort and adaptation inside the latex system.'],
      ['Made to order', 'Every model is built to the size, firmness, depth and cover you confirm.'],
    ],
    dualPlush: {
      h: 'What “Dual Plush” means',
      p: 'A latex mattress for the main support, with a separate latex topper above it for comfort and adaptation. The two are chosen together and work as one sleep system.',
    },
    families: [
      { id: 'classic', name: 'Classic Premium & Essential', says: 'The classic premium solution', line: 'Our original organic Dunlop latex: one clear firmness, or Dual Plush when you want two.', models: ['botanic', 'botanic_dp'] },
      { id: 'innov', name: 'Innovative Premium Comfort', says: 'The innovative comfort solution', line: 'A cellular-capsule latex core for Cloud Comfort and the highest ventilation in our range.', models: ['bio', 'bio_dp'] },
      { id: 'ortho', name: 'Orthopaedic Firmness', says: 'The firmer orthopaedic solution', line: 'Extra Firm latex stabilised with coconut coir, with two firm sides.', models: ['ortho'] },
      { id: 'partners', name: 'Partners', says: 'The solution for partners', line: 'Two individually regulated latex mattresses under one shared topper.', models: ['partners'] },
      { id: 'value', name: 'Best Value', says: 'The best-value solution', line: 'Optimised 100% latex: Ambient for the home, Hotel Line for hospitality.', models: ['ambient', 'hotel'] },
    ],
    models: [
      {
        id: 'botanic', name: 'Botanic', url: 'https://divinedunlop.com/products/botanic-100-organic-latex-mattress-dunlop-technology-831592302',
        img: { src: 'm-botanic.webp', w: 560, h: 207, alt: 'Botanic organic latex mattress with its quilted cover opened to show the latex core' },
        row: 'One firmness, four levels',
        title: 'The classic premium latex mattress',
        what: '100% organic Dunlop latex with a seven-zone anatomical map, made in one firmness chosen by your own body weight.',
        why: 'It is our original line: a dense, solid latex feel and a precise balance between adaptation and support.',
        who: 'Sleepers who know the one firmness they need: Soft, Medium, Firm or Extra Firm.',
        differs: [['Botanic Dual Plush', 'combines two firmnesses when you are between two levels.'], ['Ambient', 'uses a lighter latex density at a more accessible price.']],
        build: '100% organic Dunlop latex · 7-zone anatomical map',
        firm: { levels: ['s', 'm', 'f', 'x'] },
        depth: { label: 'Depths', items: ['20 cm', '24 cm', '26 cm'] },
      },
      {
        id: 'botanic_dp', name: 'Botanic Dual Plush', dp: true, url: 'https://divinedunlop.com/products/botanic-dual-plush-100-organic-latex-mattress-organic-latex-topper-dunlop-technology',
        img: { src: 'm-botanic-dp.webp', w: 560, h: 248, alt: 'Botanic Dual Plush: organic latex mattress with a separate organic latex topper above it' },
        row: 'Latex mattress + topper',
        title: 'Classic support with a regulated plush top',
        what: 'An organic Dunlop latex mattress carries the body; a separate organic latex topper above it adds comfort and adaptation. One regulated seven-zone sleep system.',
        why: 'For the sleeper on the border between two firmness levels: the latex mattress follows your weight, the topper fine-tunes the surface.',
        who: 'You want more softness and adaptation without losing support.',
        differs: [['Botanic', 'is one firmness, without a topper.'], ['Bio Comfort Dual Plush', 'puts the capsule-core Bio Comfort latex mattress underneath.']],
        build: 'Latex mattress + latex topper · separate covers or one cover',
        firm: { pairs: [['s', 'm'], ['m', 'f'], ['f', 'x']] },
        depth: { label: 'Depths', items: ['23 cm · 18 + 5', '28 cm · 20 + 8'] },
      },
      {
        id: 'bio', name: 'Bio Comfort', url: 'https://divinedunlop.com/products/bio-comfort-100-organic-latex-mattress-innovation-cloud-comfort',
        img: { src: 'm-bio.webp', w: 560, h: 226, alt: 'Bio Comfort latex mattress with its cellular-capsule core following a sleeper' },
        row: 'Capsule core, Cloud Comfort',
        title: 'Our innovative premium comfort',
        what: '100% organic Dunlop latex built around a seven-zone cellular-capsule core with a 7-Zone Synchroniser layer above it.',
        why: 'It goes beyond a classic latex core: adaptation without sinking, and the highest ventilation in our range.',
        who: 'Sleepers who want a lighter Cloud Comfort feel and a fresh, breathable sleep climate.',
        differs: [['Botanic', 'has a classic latex core and a denser, more solid feel.'], ['Bio Comfort Dual Plush', 'adds a separate plush latex topper.']],
        build: '7-zone cellular-capsule core · 7-Zone Synchroniser layer',
        firm: { levels: ['s', 'm', 'f'] },
        depth: { label: 'Depths', items: ['23 cm', '26 cm'] },
      },
      {
        id: 'bio_dp', name: 'Bio Comfort Dual Plush', dp: true, url: 'https://divinedunlop.com/products/bio-comfort-dual-plush-100-organic-latex-mattress-innovation',
        img: { src: 'm-bio-dp.webp', w: 560, h: 224, alt: 'Bio Comfort Dual Plush: capsule-core latex mattress with a plush latex topper above it' },
        row: 'Capsule core + plush topper',
        title: 'Innovative support with a plush fine-tuning layer',
        what: 'A 20 cm Bio Comfort latex mattress below and a separate seven-zone Plush latex topper above, held in place with elastic straps.',
        why: 'It joins the capsule-core support with a softer, more refined surface: the mattress carries the body, the topper refines the feel.',
        who: 'You want Bio Comfort support with more comfort freedom on top.',
        differs: [['Bio Comfort', 'is the same mattress without the topper.'], ['Botanic Dual Plush', 'also offers an Extra Firm + Firm mix.']],
        build: '20 cm Bio Comfort latex mattress + separate 7-zone Plush latex topper',
        firm: { pairs: [['s', 'm'], ['m', 'f']] },
        depth: { label: 'Depths', items: ['25 cm · 20 + 5', '28 cm · 20 + 8'] },
      },
      {
        id: 'ortho', name: 'Orthopaedic Coconut Coir', url: 'https://divinedunlop.com/products/orthopaedic-coconut-coirs-100-organic-latex',
        img: { src: 'm-ortho.webp', photo: true, w: 560, h: 420, alt: 'Cross-section of the Orthopaedic latex mattress: natural latex with coconut coir layers' },
        row: 'Extra Firm with coconut coir',
        title: 'The firmer orthopaedic solution',
        what: 'Natural Dunlop latex with coconut coir stabilising layers and seven-zone support. Two comfort sides: a Hard Extra Firm side and a Safe Firm side.',
        why: 'The coir reduces deep compression and keeps a flatter, controlled response, while the latex keeps it elastic.',
        who: 'People with orthopaedic comfort needs or a body weight over 110 kg who want a firm, flat surface. Not for anyone looking for a plush feel.',
        differs: [['Botanic Extra Firm', 'is all latex, with no coir: elastic rather than deck-like.'], ['Ambient', 'and the rest of the range adapt more and feel softer.']],
        build: 'Natural Dunlop latex + coconut coir layers · no springs, no memory foam',
        firm: { sides: ['x', 'f'], sideNames: ['Hard side', 'Safe side'] },
        depth: { label: 'Depths', items: ['17 cm', '20 cm', '25 cm'] },
      },
      {
        id: 'ambient', name: 'Ambient', url: 'https://divinedunlop.com/products/ambient-best-price-100-natural-dunlop-latex-mattress',
        img: { src: 'm-ambient.webp', w: 560, h: 277, alt: 'Ambient 100% natural Dunlop latex mattress core' },
        row: 'Best-value natural latex',
        title: 'Best value in 100% natural latex',
        what: '100% natural Dunlop latex from the first to the last centimetre, with seven-zone support, in an optimised latex density line.',
        why: 'It brings the real benefits of latex to a more accessible price, without springs, hybrid layers or hidden fillers.',
        who: 'You want a genuine latex mattress and think practically about budget.',
        differs: [['Botanic', 'uses a denser latex line for a more solid feel.'], ['Hotel Line', 'is built differently, with a shredded latex core, for hospitality.']],
        build: '100% natural Dunlop latex core · 7-zone support',
        firm: { levels: ['s', 'm', 'f', 'x'] },
        depth: { label: 'Depths', items: ['16 cm', '18 cm', '20 cm', '26 cm'] },
      },
      {
        id: 'hotel', name: 'Hotel Line', url: 'https://divinedunlop.com/products/hotel-line-optimised-value-100-dunlop-latex-mattress',
        img: { src: 'm-hotel.webp', w: 560, h: 292, alt: 'Hotel Line latex mattress with its zip cover opened' },
        row: 'Shredded latex for hotels',
        title: 'Optimised value for hotels and guest rooms',
        what: 'A pressed shredded latex core sealed between solid breathable latex sheets, in a fire-resistant zip cover.',
        why: 'Hotels, guest houses, apartments and villas need a durable, practical latex mattress that keeps the project budget under control.',
        who: 'Hospitality projects and multiple rooms. An optional seven-zone solid latex comfort layer (3, 5 or 8 cm, Medium) upgrades the feel.',
        differs: [['Ambient', 'is solid natural latex throughout; Hotel Line uses a shredded latex core.']],
        build: 'Pressed shredded latex core · solid latex sheets · optional comfort layer',
        firm: { text: [['f', 'Firm base'], ['m', 'Medium comfort layer, optional']] },
        depth: { label: 'Core', items: ['14 cm', '16 cm', '18 cm', '20 cm'] },
      },
      {
        id: 'partners', name: 'Mattress for Partners', url: 'https://divinedunlop.com/products/latex-mattress-for-partners-organic-latex',
        img: { src: 'm-partners.webp', w: 560, h: 188, alt: 'Mattress for Partners: two latex mattresses side by side under one shared latex topper' },
        row: 'Two mattresses, one topper',
        title: 'Individual comfort for two sleepers',
        what: 'Two separate 100% natural Dunlop latex mattresses, each regulated for one partner, under one shared organic latex topper.',
        why: 'Two people rarely need the same firmness. Each side is configured around one person’s own weight and proportions; the shared topper bridges the gap.',
        who: 'Couples with different comfort needs, from UK Double upwards.',
        differs: [['Every other model', 'has one regulation across the whole surface.'], ['Latex Topper for Partners', 'brings the same idea to the mattress you already have.']],
        build: 'Two latex mattresses + one shared latex topper',
        firm: { split: [['m', 'f'], ['m', 'x'], ['f', 'x']] },
        depth: { label: 'Depths', items: ['21 cm · 2 × 16 + 5', '25 cm · 2 × 20 + 5'] },
      },
    ],
  },
  topper: {
    key: 'topper',
    label: 'Latex Toppers Collection',
    url: 'https://divinedunlop.com/products/latex-toppers-collection',
    question: 'Which 100% natural latex topper is right for you?',
    lede: 'All toppers are customisable, made-to-order sleep systems in 100% natural latex rubber foam with Dunlop technology. They regulate or improve the feel of the mattress you already have.',
    buy: 'Next: on the model page choose your size, firmness, thickness and cover, then add to bag.',
    footer: ['Made to order in 100% natural latex with Dunlop technology.', 'You choose model, size, firmness, thickness and cover.', 'Regulates or improves the mattress you already have.'],
    navLabel: 'The latex topper collection',
    pick: 'Choose a topper to preview',
    steps: ['Pick your model', 'Set size, firmness, thickness & cover', 'Buy'],
    stepNotes: ['here', 'on the model page', 'on the model page'],
    principles: [
      ['You choose', 'Model, size, firmness, thickness and cover.'],
      ['The purpose', 'Regulate or improve the feel of your existing mattress.'],
      ['Seven zones', 'Every topper follows the same seven-zone Dunlop concept as our latex mattresses.'],
    ],
    families: [
      { id: 'single', name: 'Single firmness', says: 'One regulation, top to bottom', line: 'Bio Support: one natural latex layer in Soft, Medium or Firm.', models: ['t_bio'] },
      { id: 'dual', name: 'Dual firmness', says: 'Two layers, top over bottom', line: 'Bio Support Dual: a softer upper layer over a firmer lower one.', models: ['t_dual'] },
      { id: 'tpartners', name: 'Partners', says: 'Two sides, one surface', line: 'Latex Topper for Partners: a different firmness for each side.', models: ['t_part'] },
    ],
    models: [
      {
        id: 't_bio', name: 'Bio Support', url: 'https://divinedunlop.com/products/bio-support-100-organic-latex-topper-dunlop-technology',
        img: { src: 't-bio.webp', w: 640, h: 198, alt: 'Bio Support seven-zone natural latex topper' },
        row: 'One firmness, 8 to 14 cm',
        title: 'Single-firmness natural latex regulation',
        what: 'A one-layer, seven-zone organic latex topper that upgrades the mattress you already have.',
        why: 'It smooths hard spots and tired mattress behaviour on spring, foam, hybrid or latex mattresses.',
        who: 'You know the firmness you need and want to improve your current bed without replacing it.',
        differs: [['Bio Support Dual', 'puts a softer layer over a firmer one.'], ['A thicker Bio Support', 'gives a stronger correction: 8 cm light, 14 cm the most.']],
        build: 'One layer of 100% natural Dunlop latex · 7 zones · elastic corner straps',
        firm: { levels: ['s', 'm', 'f'] },
        depth: { label: 'Thickness', items: ['8 cm', '10 cm', '12 cm', '14 cm'] },
      },
      {
        id: 't_dual', name: 'Bio Support Dual', url: 'https://divinedunlop.com/products/bio-support-plus-100-organic-latex-topper',
        img: { src: 't-bio-dual.webp', w: 640, h: 227, alt: 'Bio Support Dual: two equal layers of natural latex' },
        row: 'Two layers, two firmnesses',
        title: 'Two latex layers, regulated comfort',
        what: 'Two equal, non-glued layers of organic Dunlop latex: the lower layer regulates support, the upper layer adapts to the body.',
        why: 'It removes the soft-or-firm dilemma: softness on the surface, inside a support regulation.',
        who: 'You hesitate between two firmness levels.',
        differs: [['Bio Support', 'is one firmness throughout.'], ['Latex Topper for Partners', 'splits firmness side to side, not top to bottom.']],
        build: 'Two equal organic latex layers · 7 zones · not glued',
        firm: { layers: [['s', 'm'], ['m', 'f']] },
        depth: { label: 'Thickness', items: ['10 cm · 4 + 4', '12 cm · 5 + 5', '14 cm · 6 + 6'] },
      },
      {
        id: 't_part', name: 'Latex Topper for Partners', url: 'https://divinedunlop.com/products/topper-for-partners-firm-medium-from-100-organic-latex',
        img: { src: 't-partners-sides.webp', own: true, w: 620, h: 200, alt: 'Latex Topper for Partners: a Medium section and a Firm section under one quilted topper' },
        row: 'Medium + Firm, one surface',
        title: 'One shared topper, a firmness for each side',
        what: 'Two separate organic Dunlop latex sections, one Medium and one Firm, under one shared 2 cm latex balancing layer.',
        why: 'Each partner sleeps with the regulation their body needs; the shared layer reduces the feel of the centre gap.',
        who: 'Two people with different comfort requirements sharing one bed, from Double size upwards.',
        differs: [['Bio Support Dual', 'changes firmness from top to bottom, for one sleeper.'], ['Mattress for Partners', 'is the complete two-mattress system.']],
        build: 'Medium section + Firm section · shared 2 cm latex layer',
        firm: { sides: ['m', 'f'], sideNames: ['One side', 'Other side'] },
        depth: { label: 'Thickness', items: ['10 cm', '12 cm', '14 cm', '16 cm'] },
      },
    ],
  },
};
